name: SSH Access to Runner

on: workflow_dispatch

jobs:
  ssh-access:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Access
        run: |
          # Install ngrok
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && \
          sudo apt update && sudo apt install ngrok

          # Setup SSH
          sudo apt-get install -y openssh-server
          sudo service ssh start
          
          # Create user and set password
          sudo useradd -m -s /bin/bash runner
          echo "runner:${{ secrets.SSH_PASSWORD }}" | sudo chpasswd
          sudo usermod -aG sudo runner

          # Configure SSH
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart

          # Start ngrok tunnel
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok tcp 22 > ngrok.log &
          sleep 5
          
          # Get public URL
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "SSH Access Details:" > ssh_details.txt
          echo "Host: $(echo $NGROK_URL | cut -d':' -f1 | cut -d'/' -f3)" >> ssh_details.txt
          echo "Port: $(echo $NGROK_URL | cut -d':' -f3)" >> ssh_details.txt
          echo "Username: runner" >> ssh_details.txt
          echo "Password: [Use the password set in secrets]" >> ssh_details.txt

          # Send details via Telegram
          MSG="🔐 SSH Access Details%0A%0A$(cat ssh_details.txt | sed 's/$/\\n/g')"
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=$MSG" \
            -d "parse_mode=HTML"

      - name: Keep Alive
        run: sleep 1h  # Keeps the runner alive for 1 hour
