name: SSH Access to Runner

on: workflow_dispatch

jobs:
  ssh-access:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tmate Session
        run: |
          # Install tmate
          sudo apt-get update
          sudo apt-get install -y tmate openssh-client

          # Generate SSH key
          ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
          
          # Start tmate
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          
          # Get connection strings
          SSH_CMD=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          WEB_URL=$(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')
          
          # Create details file
          echo "SSH Access Details:" > ssh_details.txt
          echo "SSH Command: \`$SSH_CMD\`%0A" >> ssh_details.txt
          echo "Web URL: $WEB_URL" >> ssh_details.txt
          echo "Note: Session will remain active for 1 hour" >> ssh_details.txt

          # Format for Telegram
          MSG="🔐 SSH Access Details%0A%0A"
          MSG+="SSH Command: $SSH_CMD%0A"
          MSG+="Web URL: $WEB_URL%0A%0A"
          MSG+="Note: Session will remain active for 1 hour"

          # Send via Telegram
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=$MSG" \
            -d "parse_mode=HTML"

      - name: Keep Alive
        run: sleep 1h  # Keeps the runner alive for 1 hour
